services:
  - type: web
    name: terravigil_ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
